services:
  # postgres db
  backend.postgres:
    image: postgres
    restart: always
    environment:
         POSTGRES_DB: ${POSTGRES_DB}
         POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
         POSTGRES_USER: ${POSTGRES_USER}
    networks:
      - backend.networks
    ports:
      - ${POSTGRES_PUBLIC_PORT}:5432
    volumes:
      - backend.api-data:/var/lib/postgresql/data