services:
  # postgres db
  backendElysia.postgres:
    image: postgres
    restart: always
    environment:
         POSTGRES_DB: ${POSTGRES_DB}
         POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
         POSTGRES_USER: ${POSTGRES_USER}
    networks:
      - backendElysia.network
    ports:
      - ${POSTGRES_PUBLIC_PORT}:5432
    volumes:
      - backendElysia.api-data:/var/lib/postgresql/data

volumes:
   backendElysia.api-data:

networks:
   backendElysia.network: