### Get ALL
GET http://localhost:3049/api/posts/
Accept: application/json

### Get By ID
GET http://localhost:3049/api/posts/9d6a2ba0-4882-4734-86b6-84f5776969e6
Accept: application/json

### Create
POST http://localhost:3049/api/posts
Content-Type: application/json

{
    "title": "Next post ever",
    "content": "We are on a roll now"
}

### Update By ID
PATCH http://localhost:3049/api/posts/9d6a2ba0-4882-4734-86b6-84f5776969e6
Content-Type: application/json

{
    "title": "Brand new title",
    "content": "This is all updated now!"
}

### Delete by ID
DELETE http://localhost:3049/api/posts/
Content-Type: application/json

{
    "id": "9bd9eeb2-88aa-49cf-aa08-45bfda74b575"
}